eGovFramework/egovframe-enterprise-business-template

pom.xml
=> Fix: Commons FileUpload 취약점 조치

DATABASE/altibase/all_ebt_data_altibase.sql, DATABASE/cubrid/all_ebt_data_cubrid.sql, DATABASE/mysql/all_ebt_data_mysql.sql, DATABASE/oracle/all_ebt_data_oracle.sql, DATABASE/tibero/all_ebt_data_tibero.sql, src/main/java/egovframework/com/cmm/web/EgovComUtlController.java, src/main/webapp/WEB-INF/jsp/main/inc/EgovIncHeader.jsp
EgovPageLink.do로 호출되는 파라미터를 link(String) 에서 linkIndex(Integer) 로 변경하였습니다.
DML의 파라미터를 동일하게 변경하였습니다.
테스트를 완료하셨으면 다음 항목에 [대문자X]로 표시해 주세요. When you're done testing, check the following items.
테스트를 진행한 브라우저를 선택해 주세요. Please select the browser(s) you ran the test on. (다중 선택 가능 you can select multiple) [X] X는 대문자여야 합니다.
테스트 전과 후의 스크린샷 또는 캡쳐 영상을 이곳에 첨부해 주세요. Please attach screenshots or video captures of your before and after tests here.
=> Fix: moveToPage() 추가 보완 조치

src/main/java/egovframework/let/cop/bbs/web/EgovBBSAdminManageController.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSManageController.java, src/main/resources/egovframework/egovProps/globals.properties, src/main/webapp/WEB-INF/jsp/cop/bbs/EgovNoticeInqire.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/EgovNoticeList.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/EgovNoticeRegist.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/EgovNoticeReply.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/EgovNoticeUpdt.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/admin/EgovNoticeInqire.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/admin/EgovNoticeList.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/admin/EgovNoticeRegist.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/admin/EgovNoticeReply.jsp, src/main/webapp/WEB-INF/jsp/cop/bbs/admin/EgovNoticeUpdt.jsp, src/main/webapp/WEB-INF/jsp/main/inc/EgovIncHeader.jsp
게시판 요청 메서드 정리
- 메뉴페이지 바로가기(goMenuPage) js post 요청을 get 요청으로 수정
- ` *   2024.08.24  이백행          요청 메서드 정리` 개정이력 수정
searchCnd, searchWrd
```java
model.addAttribute("bbsId", boardVO.getBbsId());
model.addAttribute("searchCnd", boardVO.getSearchCnd());
model.addAttribute("searchWrd", boardVO.getSearchWrd());
model.addAttribute("pageIndex", boardVO.getPageIndex());
//return "forward:/cop/bbs/selectBoardList.do";
return "redirect:/cop/bbs/selectBoardList.do";
```
```jsp
var link = '<c:url value="/" …
```
=> 게시판 요청 메서드 정리

pom.xml, src/main/resources/egovframework/egovProps/globals.properties, src/test/java/egovframework/let/uat/uia/web/EgovLoginControllerTestSelenium.java, src/test/resources/log4j2.xml
1. Selenium 라이브러리 설치
- Install a Selenium library
- https://www.selenium.dev/documentation/webdriver/getting_started/install_library/
```xml
<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-java</artifactId>
<version>4.23.1</version>
<scope>test</scope>
</dependency>
```
2. 셀레늄 사용
- Using Selenium
- https://www.selenium.dev/documentation/webdriver/getting_started/using_selenium/#examples
3. 셀레늄 단위 테스트 추가
```
2024/selenium/EgovLoginController
```
http://localhost:8080/ebt_webapp/
http://localhost:8080/ebt_webapp/uat/uia/egovLoginUsr.do
```
/uat/uia/egovLoginUsr.do
```
``` …
```
=> [로그인] 셀레늄 단위 테스트

src/main/java/egovframework/let/cop/com/web/EgovBBSUseInfoManageController.java, src/main/webapp/WEB-INF/jsp/cop/com/EgovBoardUseInfInqire.jsp, src/main/webapp/WEB-INF/jsp/cop/com/EgovBoardUseInfList.jsp, src/main/webapp/WEB-INF/jsp/cop/com/EgovBoardUseInfRegist.jsp
- searchCnd/searchWrd 추가
- `method="post"` 를 `method="get"` 으로 수정
- `return false;/JavaScript:` 제거
- ` *   2024.09.06  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/cop/com/selectBBSUseInfs.do
```
검색(Search)
```
/cop/com/selectBBSUseInfs.do
```
브랜치 생성
```
2024/search/EgovBBSUseInfoManageController
```
/egovframe-enterprise-business-template/src/main/resources/egovframework/validator/let/cop/com/EgovCopComManage.xml
`<field property="bbsNm" …
=> 게시판사용관리 검색 조건 유지

pom.xml, src/main/resources/egovframework/egovProps/globals.properties, src/test/java/egovframework/let/uat/uia/web/EgovLoginControllerTestSelenium.java, src/test/resources/log4j2.xml
v4.13.0 로 버전 수정 했습니다.
selenium jdk 8
Java 8 support in Selenium
https://www.selenium.dev/blog/2023/java-8-support/
https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/4.13.0
테스트를 완료하셨으면 다음 항목에 [대문자X]로 표시해 주세요. When you're done testing, check the following items.
테스트를 진행한 브라우저를 선택해 주세요. Please select the browser(s) you ran the test on. (다중 선택 가능 you can select multiple) [X] X는 대문자여야 합니다.
테스트 전과 후의 스크린샷 또는 캡처 영상을 이곳에 첨부해 주세요. Please attach screenshots or video captures of your before and after tests here.
https://youtu.be/qITifQcdN9U
=> [로그인] 셀레늄 단위 테스트: v4.13.0 로 버전 수정 했습니다.

src/main/java/egovframework/let/uat/uap/web/EgovLoginPolicyController.java, src/main/webapp/WEB-INF/jsp/uat/uap/EgovLoginPolicyList.jsp, src/main/webapp/WEB-INF/jsp/uat/uap/EgovLoginPolicyRegist.jsp, src/main/webapp/WEB-INF/jsp/uat/uap/EgovLoginPolicyUpdt.jsp
- ` *   2024.09.11  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/uat/uap/selectLoginPolicyList.do
```
검색(Search)
```
/uat/uap/selectLoginPolicyList.do
```
브랜치 생성
```
2024/search/EgovLoginPolicyController
```
```java
addAttributeSearch(loginPolicy, model);
//		return "forward:/uat/uap/selectLoginPolicyList.do";
return "redirect:/uat/uap/selectLoginPolicyList.do";
}
private void addAttributeSearch(LoginPolicy loginPolicy, ModelMap model) { …
```
=> [로그인정책관리] 검색 조건 유지

src/main/java/egovframework/let/uss/umt/web/EgovUserManageController.java, src/main/webapp/WEB-INF/jsp/cmm/uss/umt/EgovUserInsert.jsp, src/main/webapp/WEB-INF/jsp/cmm/uss/umt/EgovUserManage.jsp, src/main/webapp/WEB-INF/jsp/cmm/uss/umt/EgovUserPasswordUpdt.jsp, src/main/webapp/WEB-INF/jsp/cmm/uss/umt/EgovUserSelectUpdt.jsp
- 저장 버튼 클릭시 `사용자아이디 중복체크를 실행하십시오` 추가
- resultMsg 정리가 필요함
- ` *   2024.09.12  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/uss/umt/user/EgovUserManage.do
```
검색
```
/uss/umt/user/EgovUserManage.do
```
브랜치 생성
```
2024/search/EgovUserManageController
```
```java
addAttributeSearch(userManageVO, model);
//		return "forward:/uss/umt/user/EgovUserManage.do";
return "redirect:/uss/umt/user/EgovUserManage.do";
private void …
```
=> [사용자등록관리] 검색 조건 유지

src/main/java/egovframework/let/uss/ion/uas/web/EgovUserAbsnceController.java, src/main/webapp/WEB-INF/jsp/uss/ion/uas/EgovUserAbsnceList.jsp, src/main/webapp/WEB-INF/jsp/uss/ion/uas/EgovUserAbsnceRegist.jsp, src/main/webapp/WEB-INF/jsp/uss/ion/uas/EgovUserAbsnceUpdt.jsp
- ` *   2024.09.13  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/uss/ion/uas/selectUserAbsnceListView.do
```
검색
```
/uss/ion/uas/selectUserAbsnceListView.do
```
브랜치 생성
```
2024/search/EgovUserAbsnceController
```
```java
addAttributeSearch(userAbsnceVO, model);
//		return "forward:/uss/ion/uas/selectUserAbsnceList.do";
return "redirect:/uss/ion/uas/selectUserAbsnceList.do";
private void addAttributeSearch(UserAbsnceVO userAbsnceVO, …
```
=> [사용자부재관리] 검색 조건 유지

src/main/java/egovframework/let/sec/ram/web/EgovAuthorManageController.java, src/main/java/egovframework/let/sec/ram/web/EgovAuthorRoleController.java, src/main/webapp/WEB-INF/jsp/sec/ram/EgovAuthorInsert.jsp, src/main/webapp/WEB-INF/jsp/sec/ram/EgovAuthorManage.jsp, src/main/webapp/WEB-INF/jsp/sec/ram/EgovAuthorRoleManage.jsp, src/main/webapp/WEB-INF/jsp/sec/ram/EgovAuthorUpdate.jsp
- ` *   2024.09.14  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sec/ram/EgovAuthorList.do
```
검색
```
/sec/ram/EgovAuthorList.do
```
브랜치 생성
```
2024/search/EgovAuthorManageController
```
```java
addAttributeSearch(authorManageVO, model);
//			return "forward:/sec/ram/EgovAuthor.do";
return "redirect:/sec/ram/EgovAuthor.do";
private void addAttributeSearch(final AuthorManageVO authorManageVO, final Model model) { …
```
=> [권한관리] 검색 조건 유지

src/main/java/egovframework/let/sec/rgm/web/EgovAuthorGroupController.java, src/main/webapp/WEB-INF/jsp/sec/rgm/EgovAuthorGroupManage.jsp
- addAttributeSearch 메서드 추가
- ` *   2024.09.17  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sec/rgm/EgovAuthorGroupListView.do
```
검색
```
/sec/rgm/EgovAuthorGroupListView.do
```
브랜치 생성
```
2024/search/EgovAuthorGroupController
```
```java
private void addAttributeSearch(final AuthorGroupVO authorGroupVO, final Model model) {
model.addAttribute("searchCondition", authorGroupVO.getSearchCondition()); …
```
=> [사용자별권한관리] 검색 조건 유지

src/main/java/egovframework/let/sec/rmt/web/EgovRoleManageController.java, src/main/resources/egovframework/validator/let/sec/EgovSecurityManage.xml, src/main/webapp/WEB-INF/jsp/sec/rmt/EgovRoleInsert.jsp, src/main/webapp/WEB-INF/jsp/sec/rmt/EgovRoleManage.jsp, src/main/webapp/WEB-INF/jsp/sec/rmt/EgovRoleUpdate.jsp
- addAttributeSearch 메서드 추가
- ` *   2024.09.18  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
- roleManage 를 roleManageVO 로 이름 바꾸기
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sec/rmt/EgovRoleList.do
```
검색
```
/sec/rmt/EgovRoleList.do
```
브랜치 생성
```
2024/search/EgovRoleManageController
```
```java
private void addAttributeSearch(final AuthorGroupVO authorGroupVO, final Model model) {
model.addAttribute("searchCondition", authorGroupVO.getSearchCondition()); …
```
=> [롤관리] 검색 조건 유지

src/main/java/egovframework/let/sym/prm/web/EgovProgrmManageController.java, src/main/webapp/WEB-INF/jsp/sym/prm/EgovProgramListDetailSelectUpdt.jsp, src/main/webapp/WEB-INF/jsp/sym/prm/EgovProgramListManage.jsp, src/main/webapp/WEB-INF/jsp/sym/prm/EgovProgramListRegist.jsp
- addAttributeSearch 메서드 추가
- ` *   2024.09.21  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
- 할 일(TODO): 등록화면과 수정화면을 분리해야 함
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/prm/EgovProgramListManageSelect.do
```
검색
```
/sym/prm/EgovProgramListManageSelect.do
```
브랜치 생성
```
2024/search/EgovProgrmManageController
```
```java
private void addAttributeSearch(final ComDefaultVO searchVO, final Model model) {
model.addAttribute("searchCondition", searchVO.getSearchCondition()); …
```
=> [프로그램목록관리] 검색 조건 유지

src/main/java/egovframework/let/sym/mnu/mcm/web/EgovMenuCreateManageController.java, src/main/webapp/WEB-INF/jsp/sym/mnu/mcm/EgovMenuCreat.jsp, src/main/webapp/WEB-INF/jsp/sym/mnu/mcm/EgovMenuCreatManage.jsp
- addAttributeSearch 메서드 추가
- ` *   2024.09.24  이백행          컨트리뷰션 검색 조건 유지` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/mnu/mcm/EgovMenuCreatManageSelect.do
```
검색
```
/sym/mnu/mcm/EgovMenuCreatManageSelect.do
```
브랜치 생성
```
2024/search/EgovMenuCreateManageController
```
```java
private void addAttributeSearch(final ComDefaultVO searchVO, final Model model) {
model.addAttribute("searchCondition", searchVO.getSearchCondition()); …
```
=> [메뉴생성관리] 검색 조건 유지

pom.xml, src/main/java/egovframework/com/cmm/util/EgovUserDetailsHelper.java, src/test/java/egovframework/let/cop/bbs/service/impl/BBSAttributeManageDAOTestInsertBBSMasterInfTest.java, src/test/java/egovframework/let/cop/bbs/service/impl/EgovBBSAttributeManageServiceImplTestInsertBBSMastetInfTest.java, src/test/java/egovframework/let/cop/bbs/web/EgovBBSAttributeManageControllerTestInsertBBSMasterInfTest.java, src/test/java/egovframework/test/EgovTestAbstractSpring.java, src/test/java/egovframework/test/EgovTestAbstractSpringMvc.java, src/test/resources/egovframework/spring/com/test-context-common.xml, src/test/resources/egovframework/spring/com/test-context-egovuserdetailshelper.xml
- spring-test-5.3.27 추가
- Spring 테스트, Spring MVC 테스트 추가
- EgovUserDetailsHelper 추가
- /egovframe-enterprise-business-template/src/test/resources/egovframework/spring/com/test-context-common.xml 추가
- /egovframe-enterprise-business-template/src/test/resources/egovframework/spring/com/test-context-egovuserdetailshelper.xml 추가
- [게시판생성관리][BBSAttributeManageDAO.insertBBSMasterInf] DAO 단위 테스트
- [게시판생성관리][EgovBBSAttributeManageServiceImpl.insertBBSMastetInf] ServiceImpl 단위 테스트
- [게시판생성관리][EgovBBSAdminManageController.insertBBSMasterInf] Controller 단위 테스트
크롬 링크 주소 복사
``` …
```
=> [게시판생성관리][BBSAttributeManageDAO.insertBBSMasterInf] DAO 단위 테스트

src/main/java/egovframework/let/cop/bbs/service/impl/BBSAttributeManageDAO.java, src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSAttributeManageServiceImpl.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSAdminManageController.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSAttributeManageController.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/cop/bbs/SelectBBSMasterInfs.do
```
검색
```
/cop/bbs/SelectBBSMasterInfs.do
```
브랜치 생성
```
2024/di/EgovBBSAttributeManageController
```
```java
//@Repository("BBSAttributeManageDAO")
@Repository
public class BBSAttributeManageDAO extends EgovAbstractMapper {
```
```java
//@Service("EgovBBSAttributeManageService")
@Service …
```
=> [게시판생성관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/cop/com/service/impl/BBSUseInfoManageDAO.java, src/main/java/egovframework/let/cop/com/service/impl/EgovBBSUseInfoManageServiceImpl.java, src/main/java/egovframework/let/cop/com/web/EgovBBSUseInfoManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/cop/com/selectBBSUseInfs.do
```
검색
```
/cop/com/selectBBSUseInfs.do
```
브랜치 생성
```
2024/di/EgovBBSUseInfoManageController
```
```java
//@Repository("BBSUseInfoManageDAO")
@Repository
public class BBSUseInfoManageDAO extends EgovAbstractMapper {
```
```java
//@Service("EgovBBSUseInfoManageService")
@Service …
```
=> [게시판사용관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/cop/bbs/service/impl/BBSManageDAO.java, src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSManageServiceImpl.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSAdminManageController.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSManageController.java, src/main/java/egovframework/let/main/web/EgovMainController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/cop/bbs/admin/selectBoardList.do?bbsId=BBSMSTR_AAAAAAAAAAAA
```
검색
```
/cop/bbs/admin/selectBoardList.do
```
브랜치 생성
```
2024/di/EgovBBSAdminManageController
```
```java
//@Repository("BBSManageDAO")
@Repository
public class BBSManageDAO extends EgovAbstractMapper {
```
```java
//@Service("EgovBBSManageService")
@Service …
```
=> [공지사항관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sym/log/clg/service/EgovLoginLogAspect.java, src/main/java/egovframework/let/sym/log/clg/service/impl/EgovLoginLogServiceImpl.java, src/main/java/egovframework/let/sym/log/clg/service/impl/LoginLogDAO.java, src/main/java/egovframework/let/sym/log/clg/web/EgovLoginLogController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/log/clg/SelectLoginLogList.do
```
검색
```
/sym/log/clg/SelectLoginLogList.do
```
브랜치 생성
```
2024/di/EgovLoginLogController
```
```java
//@Repository("loginLogDAO")
@Repository
public class LoginLogDAO extends EgovAbstractMapper {
```
```java
//@Service("EgovLoginLogService")
@Service
public class …
```
=> [접속로그관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sts/cst/service/impl/ConectStatsDAO.java, src/main/java/egovframework/let/sts/cst/service/impl/EgovConectStatsServiceImpl.java, src/main/java/egovframework/let/sts/cst/web/EgovConectStatsController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sts/cst/selectConectStats.do
```
검색
```
/sts/cst/selectConectStats.do
```
브랜치 생성
```
2024/di/EgovConectStatsController
```
```java
//@Repository("conectStatsDAO")
@Repository
public class ConectStatsDAO extends EgovAbstractMapper {
```
```java
//@Service("conectStatsService")
@Service
public class …
```
=> [접속통계관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/uat/uap/service/impl/EgovLoginPolicyServiceImpl.java, src/main/java/egovframework/let/uat/uap/service/impl/LoginPolicyDAO.java, src/main/java/egovframework/let/uat/uap/web/EgovLoginPolicyController.java, src/main/java/egovframework/let/uat/uia/web/EgovLoginController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/uat/uap/selectLoginPolicyList.do
```
검색
```
/uat/uap/selectLoginPolicyList.do
```
브랜치 생성
```
2024/di/EgovLoginPolicyController
```
```java
//@Repository("loginPolicyDAO")
@Repository
public class LoginPolicyDAO extends EgovAbstractMapper {
```
```java
//@Service("egovLoginPolicyService")
@Service
public …
```
=> [로그인정책관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/uss/umt/service/impl/EgovUserManageServiceImpl.java, src/main/java/egovframework/let/uss/umt/service/impl/UserManageDAO.java, src/main/java/egovframework/let/uss/umt/web/EgovUserManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/uss/umt/user/EgovUserManage.do
```
검색
```
/uss/umt/user/EgovUserManage.do
```
브랜치 생성
```
2024/di/EgovUserManageController
```
```java
//@Repository("userManageDAO")
@Repository
public class UserManageDAO extends EgovAbstractMapper {
```
```java
//@Service("userManageService")
@Service
public class …
```
=> [사용자등록관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/uss/ion/uas/service/impl/EgovUserAbsnceServiceImpl.java, src/main/java/egovframework/let/uss/ion/uas/service/impl/UserAbsnceDAO.java, src/main/java/egovframework/let/uss/ion/uas/web/EgovUserAbsnceController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/uss/ion/uas/selectUserAbsnceListView.do
```
검색
```
/uss/ion/uas/selectUserAbsnceListView.do
```
브랜치 생성
```
2024/di/EgovUserAbsnceController
```
```java
//@Repository("userAbsnceDAO")
@Repository
public class UserAbsnceDAO extends EgovAbstractMapper {
```
```java
//@Service("egovUserAbsnceService")
@Service …
```
=> [사용자부재관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sec/ram/service/impl/AuthorManageDAO.java, src/main/java/egovframework/let/sec/ram/service/impl/EgovAuthorManageServiceImpl.java, src/main/java/egovframework/let/sec/ram/web/EgovAuthorManageController.java, src/main/java/egovframework/let/sec/rgm/web/EgovAuthorGroupController.java, src/main/java/egovframework/let/sec/rmt/web/EgovRoleManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sec/ram/EgovAuthorList.do
```
검색
```
/sec/ram/EgovAuthorList.do
```
브랜치 생성
```
2024/di/EgovAuthorManageController
```
```java
//@Repository("authorManageDAO")
@Repository
public class AuthorManageDAO extends EgovAbstractMapper {
```
```java
//@Service("egovAuthorManageService")
@Service
public class …
```
=> [권한관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sec/gmt/service/impl/EgovGroupManageServiceImpl.java, src/main/java/egovframework/let/sec/gmt/service/impl/GroupManageDAO.java, src/main/java/egovframework/let/sec/gmt/web/EgovGroupManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sec/gmt/EgovGroupList.do
```
검색
```
/sec/gmt/EgovGroupList.do
```
브랜치 생성
```
2024/di/EgovGroupManageController
```
```java
//@Repository("groupManageDAO")
@Repository
public class GroupManageDAO extends EgovAbstractMapper {
```
```java
//@Service("egovGroupManageService")
@Service
public class …
```
=> [사용자그룹관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sec/rgm/service/impl/AuthorGroupDAO.java, src/main/java/egovframework/let/sec/rgm/service/impl/EgovAuthorGroupServiceImpl.java, src/main/java/egovframework/let/sec/rgm/web/EgovAuthorGroupController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sec/rgm/EgovAuthorGroupListView.do
```
검색
```
/sec/rgm/EgovAuthorGroupListView.do
```
브랜치 생성
```
2024/di/EgovAuthorGroupController
```
```java
//@Repository("authorGroupDAO")
@Repository
public class AuthorGroupDAO extends EgovAbstractMapper {
```
```java
//@Service("egovAuthorGroupService")
@Service
public …
```
=> [사용자별권한관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sec/rmt/service/impl/EgovRoleManageServiceImpl.java, src/main/java/egovframework/let/sec/rmt/service/impl/RoleManageDAO.java, src/main/java/egovframework/let/sec/rmt/web/EgovRoleManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sec/rmt/EgovRoleList.do
```
검색
```
/sec/rmt/EgovRoleList.do
```
브랜치 생성
```
2024/di/EgovRoleManageController
```
```java
//@Repository("roleManageDAO")
@Repository
public class RoleManageDAO extends EgovAbstractMapper {
```
```java
//@Service("egovRoleManageService")
@Service
public class …
```
=> [롤관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sym/mnu/mpm/web/EgovMenuManageController.java, src/main/java/egovframework/let/sym/prm/service/impl/EgovProgrmManageServiceImpl.java, src/main/java/egovframework/let/sym/prm/service/impl/ProgrmManageDAO.java, src/main/java/egovframework/let/sym/prm/web/EgovProgrmManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/prm/EgovProgramListManageSelect.do
```
검색
```
/sym/prm/EgovProgramListManageSelect.do
```
브랜치 생성
```
2024/di/EgovProgrmManageController
```
```java
//@Repository("progrmManageDAO")
@Repository
public class ProgrmManageDAO extends EgovAbstractMapper {
```
```java
//@Service("progrmManageService")
@Service …
```
=> [프로그램목록관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sym/mnu/mcm/service/impl/EgovMenuCreateManageServiceImpl.java, src/main/java/egovframework/let/sym/mnu/mcm/service/impl/MenuCreateManageDAO.java, src/main/java/egovframework/let/sym/mnu/mcm/web/EgovMenuCreateManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/mnu/mcm/EgovMenuCreatManageSelect.do
```
검색
```
/sym/mnu/mcm/EgovMenuCreatManageSelect.do
```
브랜치 생성
```
2024/di/EgovMenuCreateManageController
```
```java
//@Repository("menuCreateManageDAO")
@Repository
public class MenuCreateManageDAO extends EgovAbstractMapper {
```
```java
//@Service("meunCreateManageService")
@Service …
```
=> [메뉴생성관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/main/web/EgovMainController.java, src/main/java/egovframework/let/sym/mnu/mpm/service/impl/EgovMenuManageServiceImpl.java, src/main/java/egovframework/let/sym/mnu/mpm/service/impl/MenuManageDAO.java, src/main/java/egovframework/let/sym/mnu/mpm/web/EgovMenuManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/mnu/mpm/EgovMenuManageSelect.do
```
검색
```
/sym/mnu/mpm/EgovMenuManageSelect.do
```
브랜치 생성
```
2024/di/EgovMenuManageController
```
```java
//@Repository("menuManageDAO")
@Repository
public class MenuManageDAO extends EgovAbstractMapper {
```
```java
//@Service("meunManageService")
@Service
public class …
```
=> [메뉴목록관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sym/ccm/cca/web/EgovCcmCmmnCodeManageController.java, src/main/java/egovframework/let/sym/ccm/ccc/service/impl/CmmnClCodeManageDAO.java, src/main/java/egovframework/let/sym/ccm/ccc/service/impl/EgovCcmCmmnClCodeManageServiceImpl.java, src/main/java/egovframework/let/sym/ccm/ccc/web/EgovCcmCmmnClCodeManageController.java, src/main/java/egovframework/let/sym/ccm/cde/web/EgovCcmCmmnDetailCodeManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/ccm/ccc/EgovCcmCmmnClCodeList.do
```
검색
```
/sym/ccm/ccc/EgovCcmCmmnClCodeList.do
```
브랜치 생성
```
2024/di/EgovCcmCmmnClCodeManageController
```
```java
//@Repository("CmmnClCodeManageDAO")
@Repository
public class CmmnClCodeManageDAO extends EgovAbstractMapper {
```
```java
//@Service("CmmnClCodeManageService")
@Service …
```
=> [분류코드관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sym/ccm/cca/service/impl/CmmnCodeManageDAO.java, src/main/java/egovframework/let/sym/ccm/cca/service/impl/EgovCcmCmmnCodeManageServiceImpl.java, src/main/java/egovframework/let/sym/ccm/cca/web/EgovCcmCmmnCodeManageController.java, src/main/java/egovframework/let/sym/ccm/cde/web/EgovCcmCmmnDetailCodeManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/ccm/cca/EgovCcmCmmnCodeList.do
```
검색
```
/sym/ccm/cca/EgovCcmCmmnCodeList.do
```
브랜치 생성
```
2024/di/EgovCcmCmmnCodeManageController
```
```java
//@Repository("CmmnCodeManageDAO")
@Repository
public class CmmnCodeManageDAO extends EgovAbstractMapper {
```
```java
//@Service("CmmnCodeManageService")
@Service …
```
=> [공통코드관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sym/ccm/cde/service/impl/CmmnDetailCodeManageDAO.java, src/main/java/egovframework/let/sym/ccm/cde/service/impl/EgovCcmCmmnDetailCodeManageServiceImpl.java, src/main/java/egovframework/let/sym/ccm/cde/web/EgovCcmCmmnDetailCodeManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/ccm/cde/EgovCcmCmmnDetailCodeList.do
```
검색
```
/sym/ccm/cde/EgovCcmCmmnDetailCodeList.do
```
브랜치 생성
```
2024/di/EgovCcmCmmnDetailCodeManageController
```
```java
//@Repository("CmmnDetailCodeManageDAO")
@Repository
public class CmmnDetailCodeManageDAO extends EgovAbstractMapper {
```
```java …
```
=> [상세코드관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/sym/ccm/zip/service/impl/EgovCcmExcelZipMapping.java, src/main/java/egovframework/let/sym/ccm/zip/service/impl/EgovCcmZipManageServiceImpl.java, src/main/java/egovframework/let/sym/ccm/zip/service/impl/ZipManageDAO.java, src/main/java/egovframework/let/sym/ccm/zip/web/EgovCcmZipManageController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/sym/ccm/zip/EgovCcmZipList.do
```
검색
```
/sym/ccm/zip/EgovCcmZipList.do
```
브랜치 생성
```
2024/di/EgovCcmZipManageController
```
```java
//@Repository("ZipManageDAO")
@Repository
public class ZipManageDAO extends EgovAbstractMapper {
```
```java
//@Service("ZipManageService")
@Service
public class …
```
=> [우편번호관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/cop/bbs/service/impl/BBSManageDAO.java, src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSManageServiceImpl.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSAdminManageController.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSManageController.java, src/main/java/egovframework/let/main/web/EgovMainController.java
크롬 링크 주소 복사
```
http://localhost:8080/ebt_webapp/cop/bbs/selectBoardList.do?bbsId=BBSMSTR_AAAAAAAAAAAA
```
검색
```
/cop/bbs/selectBoardList.do
```
브랜치 생성
```
2024/di/EgovBBSManageController
```
```java
//@Repository("BBSManageDAO")
@Repository
public class BBSManageDAO extends EgovAbstractMapper {
```
```java
//@Service("EgovBBSManageService")
@Service …
```
=> [공지사항] 롬복 생성자 기반 종속성 주입
